feat: create card component
ThinkFiveable/open pull request #23
Opened 2021-03-22 16:46 UTC by eilla1

create project card component with dummy data

closes Unfinished Card Component #15

2021-03-22 16:51 UTC, zaida04 commented
Gonna wait on Sarthaks review first since I'm not a frontend person.

2021-03-22 17:11 UTC, sarthaktexas commented
Card component looks awesome but looks like the grid is messed up, let me check your code and i'll comment on it.

2021-03-22 17:16 UTC, sarthaktexas requested changes
fix all the comments, dm me on slack or discord if you don't understand why i said it or if you need help fixing it

2021-03-22 17:16 UTC, sarthaktexas commented on components/card.js
> +                style={{ borderColor: `${featureColor}` }}
no need for a template string, remove it cause the variable can get passed it directly

2021-03-22 17:16 UTC, sarthaktexas commented on pages/index.js
> +                <svg className="-z-5 transform rotate-180 -mt-1 md:-mt-5" viewBox="0 0 1440 320">
what's this class? that's not a thing in tailwind iirc

2021-03-22 17:16 UTC, sarthaktexas commented on pages/index.js
> +                        featureColor="gold"
change the prop to award maybe??

2021-03-22 17:16 UTC, sarthaktexas commented on pages/index.js
> +                        projectType="Discord Bot"
why are we using z indices everywhere

2021-03-22 17:16 UTC, sarthaktexas commented on pages/index.js
> +                        featureColor="white"
there's no white feature color?

2021-03-22 17:16 UTC, sarthaktexas commented on components/card.js
> +                className="rounded-xl h-40 w-72 overflow-hidden border-4">
don't overflow hidden, that doesn't make sense here

2021-03-22 17:16 UTC, sarthaktexas commented on pages/index.js
> +                <div className="z-40 justify-center flex flex-wrap space-x-12">
this is the problem, use grid instead of flexbox, flexbox is used for layouts that follow row and column style

2021-03-22 22:12 UTC, eilla1 commented on components/card.js
> +                className="rounded-xl h-40 w-72 overflow-hidden border-4">
without overflow hidden, the image flows outside the dimensions of the div. is there a better solution to this than `overflow-hidden`?
<img width="551" alt="image overflowing" src="https://user-images.githubusercontent.com/72365100/112064904-f58ffa00-8b20-11eb-9569-7fb2c42f4626.png">
)

2021-03-23 02:17 UTC, sarthaktexas approved these changes
great

2021-03-23 02:17 UTC, sarthaktexas commented
can somebody else mark this as resolved

2021-03-23 02:18 UTC, zaida04 approved these changes

2021-03-23 02:19 UTC, merged