fix: enlarge cards and grid gap
ThinkFiveable/open pull request #28
Opened 2021-03-23 07:18 UTC by eilla1

addressed styling issues with card size and spacing between cards

fixes Styling issues with Variant 1 of Card #26

2021-03-23 07:23 UTC, sarthaktexas requested changes
still doesn't spam entire screen, gap too big on mobile, change the gap depending on device size

2021-03-23 07:24 UTC, sarthaktexas requested changes

2021-03-23 07:24 UTC, sarthaktexas commented on pages/index.js
> +                <div className="justify-center grid sm:grid-flow-row lg:grid-flow-col gap-12">
if this isn't the fanciest trying i've ever seen, just do a manual 3 column layout lol and then change it to 2 on sm and above and then 1 on mobile

2021-03-23 22:48 UTC, awlevin commented
#### 📝Changed routes:


| [**/**](https://open-1kydj4gvs-thinkfiveable.vercel.app/) |
|:-:|
|<a href="https://open-1kydj4gvs-thinkfiveable.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/7_SNWINOH7I__2Wqw_U728J_iKs_.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/_TuGw7vLgDn3LkGiFzfedf_ayJM_.png">(view full size)</a> |







Commit f2905961e32877d99e540aeba524c5c576c94eef (https://open-1kydj4gvs-thinkfiveable.vercel.app).

2021-03-23 23:11 UTC, sarthaktexas commented on pages/index.js
> +                <div className="mx-8 justify-center grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
are you trying to center it? if so, just do:
```suggestion
                <div className="mx-auto justify-center grid sm:grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-12">
```

2021-03-24 01:01 UTC, sarthaktexas approved these changes

2021-03-24 06:13 UTC, awlevin commented
Wait what's this "changed routes" comment i left.....? I _swear_ that wasn't me

2021-03-24 06:47 UTC, sarthaktexas commented
@awlevin it's called vercel commit preview, you enabled it. i got an email too if you want proof.

2021-03-24 07:15 UTC, awlevin commented
lmao awkward. had a weird hunch that might’ve been what it was. when I enabled it earlier (mostly intended for a private repo) for some reason I thought it had more to do with preview deploy summaries (like build sizes etc.). 

I presume we can disable it on a per-project basis, and can look into that if we want... unless we like it? Curious what others think.

2021-03-24 07:17 UTC, sarthaktexas commented
I like it cause I can see the desktop preview on mobile cause I review most of not a of the PRs (i'm typing this too) on mobile.

2021-03-27 20:34 UTC, zaida04 approved these changes

2021-03-27 20:34 UTC, merged