chore: submission guidelines
ThinkFiveable/open pull request #34
Opened 2021-04-02 23:00 UTC by zaida04

closes #19

2021-04-03 00:09 UTC, eilla1 requested changes

2021-04-03 00:09 UTC, eilla1 commented on SUBMISSION_GUIDELINES.md
> +- Projects must have a clear CODE_OF_CONDUCT.md that clearly denounces any discriminatory, unwelcoming, or any otherwise harmful behavior that damages/hinders the positive environment we've strived t
Should we link an example code of conduct? https://www.contributor-covenant.org/version/2/0/code_of_conduct/ perhaps

2021-04-03 00:09 UTC, eilla1 commented on SUBMISSION_GUIDELINES.md
> +- If the project is a fork, it must be transformative to an extent (??).
Maybe we could evaluate these types of projects on a case-by-case basis. Also the `(??)`

2021-04-03 18:11 UTC, eilla1 commented on SUBMISSION_GUIDELINES.md
> +- If the project is a fork, it must be transformative to an extent. This will be decided on a case by case basis
small thing, but can you add a period at the end please? 😄

2021-04-03 19:04 UTC, eilla1 approved these changes
Thanks!

2021-04-05 00:51 UTC, sarthaktexas approved these changes

2021-04-05 00:52 UTC, merged