feat: add mdx and about page
ThinkFiveable/open pull request #36
Opened 2021-04-05 06:41 UTC by eilla1

2021-04-05 06:44 UTC, eilla1 commented
![z-index: it no work :sadge:](https://user-images.githubusercontent.com/72365100/113545738-965dcb00-959f-11eb-9bd5-29e0894ec69f.PNG)

@sarthaktexas should i get the text to overlap with the svg or move it down?

2021-04-05 16:18 UTC, zaida04 commented
I think the design would look really cool if the text would overlap with the svg. Otherwise it just feels like a lot of blank space.

2021-04-05 16:30 UTC, sarthaktexas requested changes
Other than that comment I think it's fine. And yes, overlap them, I want to see how it looks.

2021-04-05 16:30 UTC, sarthaktexas commented on styles/globals.css
> +@layer base {
nonono. i didn't mention this cause i thought you knew. remove this and do something like this in `_app.js`:

```js
import '../styles/globals.css';
import { MDXProvider } from '@mdx-js/react'
import MDXComponents from '../components/MDXComponents'
import { AuthProvider } from '../lib/auth'

function MyApp({ Component, pageProps }) {
  return (
    <AuthProvider>
      <MDXProvider components={MDXComponents}>
          <Component {...pageProps} />
      </MDXProvider>
    </AuthProvider>
  );
}

export default MyApp;
```

and then in `MDXComponents.js`:
```js

const CustomLink = (props) => {
    const href = props.href;
    const isInternalLink = href && (href.startsWith('/') || href.startsWith('#'));

    if (isInternalLink) {
        return (
            <Link href={href}>
                <a {...props} />
            </Link>
        );
    }

    return <a target="_blank" rel="noopener noreferrer" {...props} />;
};

const CustomHeader = (props) => {
    return (
        <h1 className="text-xl font-bold mt-4 mb-1" {...props} />
    )
}

const MDXComponents = {
    h1: CustomHeader,
    a: CustomLink,
};

export default MDXComponents;
```
> By the way, the link component above automatically put `next/link` when it's a client side redirect :)

2021-04-06 08:43 UTC, awlevin commented
#### 📝Changed routes:


| [**/about**](https://open-kh7vhu5yb-thinkfiveable.vercel.app/about) | [**/**](https://open-kh7vhu5yb-thinkfiveable.vercel.app/) |
|:-:|:-:|
|<a href="https://open-kh7vhu5yb-thinkfiveable.vercel.app/about"><img src="https://images.weserv.nl?url=https://s.microlink.io/3aRjXvCnZ6PDF6c0BEKt_c_e37IlBk28PKLWXgsOHxi4InEwhYKseKvNVccHDzV7heUimQtWndt2Mlrf8yvEpg.png&w=600" alt="Screenshot of /about" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/YpWY0V9RCAQQdbvBl1pT88kTScBEwRhi8cORRUeuqFqT_9q8DZEtNu0C6CNaTEeYzTgqswmIUEOXcWvpQwb2Nw.png">(view full size)</a> |<a href="https://open-kh7vhu5yb-thinkfiveable.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/OQtXpXgk0L9m44ldx-ThXZla4r27OXUd6zxPSYAthFEzCdzTyZzsWqVsLCPgmSmHKjiu0iWCLQpxxFygZ4nGLA.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/LzN6U04ShPp5pSeeimKEwbq-KA9K4OB2kLewUOk5xI_-QhLEis10HLdhSoIpcHRk8jhM6Pqg3Di0CN1hPjjuhQ.png">(view full size)</a> |







Commit b6cdeddbedbf04d2767383dbcf72d4346bc53af4 (https://open-kh7vhu5yb-thinkfiveable.vercel.app).

2021-04-06 14:49 UTC, zaida04 commented
I'd like us to have a heading on top of https://github.com/ThinkFiveable/open/pull/36/files#diff-62560091290dc9edebbff8bb0ff6f88a3eacb7ef5fbec9e4b320ddd54b44d55cR5, otherwise the body text looks out of place.

Can we also make the mouse pointer change when people hover over `Learn More`? Right now the mouse pointer stays the same when hovering over the Learn More button.

2021-04-07 22:32 UTC, zaida04 submitted a review, later dismissed
Thank you so much Ella! Looks dope 🔥

2021-04-08 23:19 UTC, sarthaktexas requested changes

2021-04-08 23:19 UTC, sarthaktexas commented on pages/index.js
> +                        <div className="font-rubik font-medium bg-black text-center rounded-full px-5 py-1 text-lg text-white w-fitcontent flex flex-row cursor-pointer">
Make this an anchor tag

2021-04-08 23:24 UTC, sarthaktexas approved these changes
'

2021-04-08 23:24 UTC, zaida04 approved these changes

2021-04-08 23:24 UTC, merged