meta: add project submission batch
ThinkFiveable/open pull request #46
Opened 2021-04-16 01:21 UTC by zaida04

This adds:
- https://github.com/DBlack2021/movie-picker
- https://github.com/ThinkFiveable/maya
- https://github.com/guildedjs/guilded.js

2021-04-16 01:29 UTC, eilla1 approved these changes, later dismissed

2021-04-16 04:14 UTC, eilla1 submitted a review, later dismissed

2021-04-17 06:15 UTC, eilla1 approved these changes, later dismissed

2021-04-17 21:04 UTC, sarthaktexas requested changes
based on the other PR, remove `repoOwnerIcon`

2021-04-17 22:29 UTC, RayhanADev commented on data/PROJECTS.json
> +        "repoName": "DeltaScheme",
Hmm, it seems ya'll need a repoLogo xD. Here you go: [https://github.com/RayhanADev/DeltaScheme/blob/master/public/assets/images/logos/deltascheme_opengraphimage.png](https://github.com/RayhanADev/DeltaScheme/blob/master/public/assets/images/logos/deltascheme_opengraphimage.png)



Hmm it seems yya'll

2021-04-19 03:15 UTC, eilla1 approved these changes

2021-04-19 03:30 UTC, sarthaktexas approved these changes

2021-04-19 03:30 UTC, merged