refactor: index
ThinkFiveable/open pull request #47
Opened 2021-04-16 01:44 UTC by zaida04

This PR changes some var names for consistency,
Adds a default image for projects without an image, using the vercel open graph image as a service api instead of relying on a random image.
Cards now are linked to their respective project.

2021-04-16 03:34 UTC, eilla1 approved these changes, later dismissed

2021-04-17 06:17 UTC, awlevin commented
#### 📝Changed routes:


| [**/**](https://open-8y8hb8h49-thinkfiveable.vercel.app/) |
|:-:|
|<a href="https://open-8y8hb8h49-thinkfiveable.vercel.app/"><img src="https://images.weserv.nl?url=https://s.microlink.io/xmU-WPkyqo3tX5KdGuHw88WX5lSqtXOzVxALu7bvKYa5kUKgCfZSFVAPZOB27RMMwsrZ6HJ45JG693AwM695Xw.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://s.microlink.io/m8zHtBFr5DCcJ_IsdsVLrSlOkO6nVH_APpv-TGUvxL800IZBuSuPCtGiE5I6PDxtVq2fY-kdJksr5JQWL91Cdw.png">(view full size)</a> |







Commit c5fc7847cc7541e53f1a909e49bf3320de4f95c8 (https://open-8y8hb8h49-thinkfiveable.vercel.app).

2021-04-17 21:00 UTC, sarthaktexas requested changes

2021-04-17 21:00 UTC, sarthaktexas commented on pages/index.js
>                          return (
you don't put two return statements in each other.

2021-04-17 21:00 UTC, sarthaktexas commented on pages/index.js
>                      {RepoData.map(({ repoName, repoOwner, projectType, repoLogo, repoOwnerIcon, award }) => {
```suggestion
                    {RepoData.map(({ repoName, repoOwner, projectType, repoLogo, repoOwnerIcon, award }) => (
```

2021-04-17 21:00 UTC, sarthaktexas commented on pages/index.js
>                          );
```suggestion                        
```

2021-04-17 21:00 UTC, sarthaktexas commented on pages/index.js
>                      })}
```suggestion
                    ))}
```

2021-04-17 21:03 UTC, sarthaktexas requested changes

2021-04-17 21:03 UTC, sarthaktexas commented on data/PROJECTS.json
>          "repoOwnerIcon": "https://avatars.githubusercontent.com/u/76849512?v=4",
this isn't needed.
```suggestion
```

2021-04-17 21:03 UTC, sarthaktexas commented on data/PROJECTS.json
>          "repoOwnerIcon": "https://avatars.githubusercontent.com/u/66260572?v=4",
```suggestion
```

2021-04-17 21:03 UTC, sarthaktexas commented on pages/index.js
> +                                            repoOwnerIcon ??
```suggestion
```

2021-04-17 21:03 UTC, sarthaktexas commented on pages/index.js
> +                                            "https://avatars.githubusercontent.com/u/76849512?v=4"
```suggestion
                                            "https://avatars.githubusercontent.com/" + repoOwner
```

2021-04-19 03:15 UTC, eilla1 approved these changes

2021-04-19 03:31 UTC, sarthaktexas approved these changes

2021-04-19 03:31 UTC, merged