fix: search card broken images
ThinkFiveable/open pull request #54
Opened 2021-04-20 01:28 UTC by zaida04

this bronk, me do fix
![image](https://user-images.githubusercontent.com/19440022/115323421-1cf4d980-a156-11eb-8f4e-c0359b08ab0a.png)

2021-04-20 04:06 UTC, eilla1 reviewed
<img width="947" alt="Screen Shot 2021-04-19 at 9 04 09 PM" src="https://user-images.githubusercontent.com/72365100/115335910-fe411380-a152-11eb-9f61-cc04ae62bf19.png">

pfp isn't working on search page

2021-04-20 05:14 UTC, jasonappah commented on pages/search.js
>                                      profileIcon={repoOwnerIcon}
change this to ``profileIcon={`https://avatars.githubusercontent.com/${repoOwner}`}``

2021-04-21 00:18 UTC, sarthaktexas requested changes

2021-04-21 00:18 UTC, sarthaktexas commented on pages/search.js
>                              return (
i thought i told yall this before but remove the double returns you can just do `=> (` instead of `=> { return (`

2021-04-21 17:49 UTC, eilla1 approved these changes

2021-04-23 00:57 UTC, sarthaktexas approved these changes

2021-04-23 00:57 UTC, merged