feat: dark mode
ThinkFiveable/open pull request #60
Opened 2021-04-28 17:41 UTC by googol88

This PR implements the long-awaited dark mode across the Fiveable Open Source website. 🌙

Because there is work to be done on implementing a toggle and fixing styles for the search bar and GitHub link, the PR will be a draft. Also, the `.github` folder was deleted because of conflicts with GitHub Actions requiring some sort of PAT I couldn't figure out.

Closes #29.

2021-04-28 17:54 UTC, zaida04 commented
Before this PR gets to a review point, I'm gonna ask that the `.github` dir be reinstated. We can work together to resolve whatever conflict is coming up, but before this gets merged that dir needs to be there.

2021-04-28 21:21 UTC, googol88 commented
I made a lot of unnecessary commits here, but I think that should be resolved now :)

2021-04-28 21:47 UTC, awlevin commented
Wow, this is an awesome contribution!! Thanks @googol88!

2021-04-29 02:13 UTC, zaida04 commented
btw you accidentally pushed the files as `.github/lint.yml` and `.github/build.yml` instead of `.github/workflows/lint.yml` and `.github/workflows/build.yml`.

2021-04-29 18:18 UTC, googol88 commented
Alright, I've implemented the dark mode toggle. In the process I've also changed the GitHub icon for consistency. There's a bit of touching up with the search bar focus styles, but I still have some issues with responsiveness on small viewports. Let me know what you think!

2021-04-29 20:16 UTC, eilla1 approved these changes
Looks awesome, thanks @googol88! 🌙

2021-05-02 13:27 UTC, googol88 commented
Hi, is the PR ready to be merged? @sarthaktexas @zaida04 would greatly appreciate it if you could take a quick look!

2021-05-02 16:18 UTC, zaida04 commented
Hey, I've taken a look and have only one change to request.

Can we make the images stretch to fill the container height-wise? And also make a white background for all the images in the event the image is transparent?
![image](https://user-images.githubusercontent.com/19440022/116819908-53f8c100-ab40-11eb-99de-040cbb9795ad.png)

2021-05-02 20:12 UTC, zaida04 approved these changes
Again, thank you so much for your contribution. This dark mode looks awesome! Due to the big scope of the impact this has on the design, I'm gonna get Sarthak to also approve this before it's merged.

2021-05-02 21:05 UTC, sarthaktexas requested changes
i'm requesting 2 changes but don't change them if theyre needed and respond to some of the comments i posted

2021-05-02 21:05 UTC, sarthaktexas commented on components/footer.js
> +                className="fill-current text-black dark:text-gray -mb-2"
no clue what this does i'll review it later when i'm on my computer

2021-05-02 21:05 UTC, sarthaktexas commented on components/card.js
> +                    <img src={profileIcon} className="rounded-full h-full w-12 float-right" alt="Profile" />
not sure if this causes the image to be horizontally squished, i'll check when i'm on my computer

2021-05-02 21:05 UTC, sarthaktexas commented on components/layout.js
> +                className="fill-current text-blue dark:text-blue-dark transform rotate-180 -mt-1 md:-mt-5 z-0 absolute"
same as the comment on the other svg

2021-05-02 21:05 UTC, sarthaktexas commented on components/nav.js
> +                            <a className="p-3 block rounded-full hover:bg-black dark:hover:bg-white hover:bg-opacity-10 dark:hover:bg-opacity-10 transform duration-200">
what does this transform do here? there's nothing happening that needs this class

2021-05-02 21:05 UTC, sarthaktexas commented on components/nav.js
> +                            <CgDarkMode size={32} />
not sure if is size works cause it seems a little big, i'll check this later

2021-05-02 21:05 UTC, sarthaktexas commented on pages/index.js
> -                        fill="#c1e8ed"
wow this is smart i don't know why i didn't think of this

it's funny because i told @eilla1 to do this on her repo but i didn't do it myself

2021-05-02 21:05 UTC, sarthaktexas commented on pages/index.js
> +                                key={repoName}
THANK YOU

2021-05-02 21:05 UTC, sarthaktexas commented on tailwind.config.js
> +                    dark: "#01A0B6"
awesome use of variants, thank you

2021-05-02 21:06 UTC, googol88 commented on pages/index.js
> +                                key={repoName}
YOU'RE WELCOME

2021-05-02 21:07 UTC, sarthaktexas commented
found this issue
![image](https://user-images.githubusercontent.com/28282096/116827786-77336880-ab60-11eb-915d-26d0b5064bad.jpeg)

2021-05-02 23:04 UTC, zaida04 commented on components/card.js
> +                    <img src={profileIcon} className="rounded-full h-full w-12 float-right" alt="Profile" />
That change I accidentally made when I was trying to stretch repo preview images. Will revert

2021-05-13 19:15 UTC, sarthaktexas approved these changes

2021-05-13 19:15 UTC, merged